"""
Django settings for DjangoTraders project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/

TEMPLATES' context_processors (below) include
djtraders.session_context.current_employee/current_customer, so
base.html's navbar can show the logged-in employee/customer on every
page (see each function's own docstring in djtraders/session_context.py).
INSTALLED_APPS includes crispy_forms/crispy_bootstrap5, which render a
Django Form as Bootstrap 5 markup via {% crispy %} (see
CRISPY_ALLOWED_TEMPLATE_PACKS/CRISPY_TEMPLATE_PACK below and
djtraders/forms.py).
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6d_#ekptae2f7tcjel+%(it8p(-*xpq2p^wtvpz92^d=h76c(9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # admin (below) is the only one of these four core apps this project
    # uses directly (DjangoTraders/urls.py wires up /admin/) -- auth,
    # contenttypes, and messages aren't otherwise touched by djtraders'
    # own hand-rolled sessions/logins, but the admin site itself depends
    # on all three (user/permission management, content-type lookups,
    # and its own flash-message banners), so they stay installed.
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Ships the intcomma template filter (thousands-separator formatting,
    # e.g. 1234.5 -> "1,234.50") used for every currency value across
    # djtraders' templates -- see those templates' own comments for
    # where it's loaded and applied.
    'django.contrib.humanize',
    # region [CONCEPT] crispy_forms/crispy_bootstrap5
    # django-crispy-forms renders a Django Form/ModelForm as styled HTML
    # via {% load crispy_forms_tags %}/{% crispy form %} in a template,
    # instead of hand-writing every <input>/<label> yourself.
    # crispy_bootstrap5 is the "template pack" that tells it to render
    # using Bootstrap 5's markup/classes (matching this project's own
    # Bootstrap version) -- selected below via CRISPY_TEMPLATE_PACK.
    # endregion
    'crispy_forms',
    'crispy_bootstrap5',
	'djtraders',
]

# region [CONCEPT] crispy-forms template pack selection
# CRISPY_ALLOWED_TEMPLATE_PACKS lists which packs are installed;
# CRISPY_TEMPLATE_PACK picks the one {% crispy %} actually renders with.
# "bootstrap5" matches the Bootstrap 5.3 this project already loads in
# templates/common/base.html.
# endregion
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoTraders.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS lists template folders that live outside any single app --
        # used here for project-level pages (like the site home page)
        # that don't belong to djtraders or any other specific app.
        # APP_DIRS=True (below) is what makes each app's own
        # templates/ folder (e.g. djtraders/templates/) get found too;
        # DIRS and APP_DIRS work together, not as alternatives.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Adds current_employee (djtraders/session_context.py) to
                # every template's context, for base.html's login/logout navbar.
                'djtraders.session_context.current_employee',
                # Same idea for the customer-facing login -- adds
                # current_customer (djtraders/session_context.py) to every
                # template's context.
                'djtraders.session_context.current_customer',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoTraders.wsgi.application'


# Database: 
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
		"ENGINE": "django.db.backends.postgresql",
		"NAME": "DjangoTraders",
		"USER": "postgres",
		"PASSWORD": "P8707",
		"HOST": "localhost",
		"PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# region [CONCEPT] STATICFILES_DIRS vs. per-app static/ folders
# STATICFILES_DIRS lists static folders that live outside any single
# app -- the same idea as TEMPLATES['DIRS'] above, but for static files
# instead of templates. Without this, Django's staticfiles app only
# finds each installed app's own static/ folder (e.g. an app's
# static/<app_name>/ -- there's no such folder in this project
# currently, since djtraders/static/djtraders/css/site.css was removed
# once the app converted to Bootstrap). This entry adds the project-root
# static/ folder, which is where static/common/DjangoTraders.css and
# static/common/DjangoTraders.js live -- project-wide assets that
# aren't tied to any one app, referenced from templates/common/base.html.
# endregion
STATICFILES_DIRS = [BASE_DIR / 'static']
